services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata_test
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - suricata-logs:/var/log/suricata
      - suricata-rules:/var/lib/suricata
      - suricata-config:/etc/suricata
    # !!! YOU MUST CHANGE 'eno1' to your NUC's interface name !!!
    command: -i enp86s0

  evebox:
    image: jasonish/evebox:latest
    container_name: evebox_ui
    restart: unless-stopped
    ports:
      - "5636:5636"
    volumes:
      - suricata-logs:/var/log/suricata:ro
      - evebox-data:/var/lib/evebox
    command: >
      evebox server
      --datastore sqlite
      --data-directory /var/lib/evebox
      --input /var/log/suricata/eve.json

volumes:
  suricata-logs:
  suricata-rules:
  suricata-config:
  evebox-data:
